### PR TITLE
Add support for SSSP v1.2

### PR DESCRIPTION
**Pull request by mbercx**

### CODE REVIEW

**Comment by sphuber** [comment]
Any reason this is still a draft? Is anything else needed?

**Comment by mbercx** [comment]
I was still testing it but already wanted to share the update. Seems to be working fine though, so I'll change it to ready for review.

**Review by sphuber — APPROVED** [review]
Thanks, all good to go

**Comment by unkcpz** [comment]
Hi both, I have updated the SSSP version to `1.2.1`, I guess there is no need to update this repo since it will read the `versions.yaml` to use the latest patch version, correct?

**Comment by sphuber** [comment]
Indeed, see here:
https://github.com/aiidateam/aiida-pseudo/blob/9ea1570a584c274627d65b97a9f8bc0de788ab11/src/aiida_pseudo/cli/install.py#L116

**Pull request merged**
